COMMON_OBJS =
COMMON_LIBS =
COMMON_DEPS = $(COMMON_OBJS:.o=.d)

-include $(COMMON_DEPS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<
	$(CXX) -MM $(CXXFLAGS) $< > $*.d

clean_common:
	/bin/rm -fv $(COMMON_OBJS) $(COMMON_DEPS)
